############################################################-*-Makefile-*-####
# Project Configuration
##############################################################################
# $Id$

##############################################################################
# Read local configuration

-include $(ROOT)/Makefile.private

##############################################################################
# Project setup

PROJECT_NAME		?= scala
PROJECT_ROOT		?= $(ROOT)
PROJECT_BINARYDIR	?= $(PROJECT_ROOT)/bin
PROJECT_LIBDIR		?= $(PROJECT_LIBRARYDIR)
PROJECT_CONFIGDIR	?= $(PROJECT_ROOT)/config
PROJECT_DOCUMENTDIR	?= $(PROJECT_ROOT)/doc
PROJECT_LIBRARYDIR	?= $(PROJECT_ROOT)/lib
PROJECT_SUPPORTDIR	?= $(PROJECT_ROOT)/support
PROJECT_SOURCEDIR	?= $(PROJECT_ROOT)/sources
PROJECT_OBJECTDIR	?= $(PROJECT_ROOT)/objects
PROJECT_WEBSITEDIR	?= $(PROJECT_ROOT)/website
PROJECT_TESTDIR		?= $(PROJECT_ROOT)/test/files
PROJECT_HTDOCSDIR	?= $(PROJECT_WEBSITEDIR)/htdocs
PROJECT_DISTRIBDIR	?= $(PROJECT_ROOT)/distribs
PROJECT_ARCHIVEDIR	?= $(PROJECT_DISTRIBDIR)
PROJECT_LISTDIR		?= $(PROJECT_CONFIGDIR)/list

##############################################################################
# External libraries

# JDK 8
ENV_JAVA_HOME		:= $(JAVA_HOME)
SCALA_JAVA_HOME		?=
SYSTEM_JAVA8_HOME	:= $(shell if [ -x /usr/libexec/java_home ]; then /usr/libexec/java_home -v 1.8 2>/dev/null; fi)
DEFAULT_JAVA_HOME	:= $(if $(SCALA_JAVA_HOME),$(SCALA_JAVA_HOME),$(if $(SYSTEM_JAVA8_HOME),$(SYSTEM_JAVA8_HOME),$(ENV_JAVA_HOME)))
JAVA_HOME		:= $(DEFAULT_JAVA_HOME)

# JRE
JRE_HOME		?= $(if $(JAVA_HOME),$(JAVA_HOME)/jre,$(PROJECT_LIBDIR)/jre)
JRE_JARFILE		?= $(JRE_HOME)/lib/rt.jar

# FJBG
FJBG_HOME		?= $(PROJECT_LIBDIR)/fjbg
FJBG_JARFILE            ?= $(BOOTSTRAP_FJBG_CLASSES)

# Ant
ANT_HOME		?= $(PROJECT_LIBDIR)/ant
ANT_JARFILE		?= $(ANT_HOME)/lib/ant.jar

##############################################################################
# Standard tools

BASENAME		?= basename
BZIP2			?= bzip2
CAT			?= cat
CHMOD			?= chmod
COMM			?= comm
CP			?= cp
CVS			?= cvs
DATE			?= date
DIRNAME			?= dirname
ECHO			?= echo
EXPR			?= expr
FIND			?= find
GREP			?= grep
GZIP			?= gzip
HEAD			?= head
IA			?= build
INSTALL			?= $(PROJECT_SUPPORTDIR)/scripts/install
JAR			= $(if $(JAVA_HOME),$(JAVA_HOME)/bin/jar,jar)
JAVA			= $(if $(JAVA_HOME),$(JAVA_HOME)/bin/java,java)
JAVAC			= $(if $(JAVA_HOME),$(JAVA_HOME)/bin/javac,javac)
LN			?= ln
M4			?= m4
MD5SUM			?= md5sum
MIRROR			?= $(PROJECT_SUPPORTDIR)/scripts/mirror
MKDIR			?= mkdir
MV			?= mv
NICE			?= nice
RECODE			?= recode
RM			?= rm -f
SCSH			?= scsh
SED			?= sed
SORT			?= sort
STAT			?= stat
TAIL			?= tail
TAR			?= tar
TOUCH			?= touch
TR			?= tr
UNIX2DOS		?= $(RECODE) ..pc
UNZIP			?= unzip
WC			?= wc
XARGS			?= xargs
ZIP			?= zip

make			?= $(MAKE) MAKELEVEL=$(MAKELEVEL) --no-print-directory

##############################################################################
# Java compiler

JAVAC_FLAGS		?= -source 8 -target 8

##############################################################################
# Scala tools

SCALA_HOME		?=
SCALA			?= $(SCALA_HOME:%=%/bin/)scala
SCALAC			?= $(SCALA_HOME:%=%/bin/)scalac
SCALAP			?= $(SCALA_HOME:%=%/bin/)scalap
SCALAINT		?= $(SCALA_HOME:%=%/bin/)scalaint
SCALARUN		?= $(SCALA_HOME:%=%/bin/)scalarun
SCALADOC		?= $(SCALA_HOME:%=%/bin/)scaladoc
SCALAINFO		?= $(SCALA_HOME:%=%/bin/)scala-info

##############################################################################
# Bootstrap compiler

BOOTSTRAP_HOME		?= $(abspath $(PROJECT_ROOT)/../v1.3.0.9-bootstrap)
BOOTSTRAP_RUNTIME_SOURCES ?= $(BOOTSTRAP_HOME)/sources
BOOTSTRAP_LIBRARY_CLASSES ?= $(BOOTSTRAP_HOME)/objects/main/lib/scala
BOOTSTRAP_RUNTIME_CLASSES ?= $(BOOTSTRAP_LIBRARY_CLASSES)
BOOTSTRAP_TOOLS_CLASSES ?= $(BOOTSTRAP_HOME)/objects/main/lib/tools
BOOTSTRAP_FJBG_CLASSES ?= $(BOOTSTRAP_HOME)/lib/fjbg/fjbg.jar
BOOTSTRAP_SCALAC	?= JAVA_HOME=$(JAVA_HOME) \
			   SCALA_RUNTIME_SOURCES=$(BOOTSTRAP_RUNTIME_SOURCES) \
			   SCALA_RUNTIME_CLASSES=$(BOOTSTRAP_RUNTIME_CLASSES) \
			   SCALA_TOOLS_CLASSES=$(BOOTSTRAP_TOOLS_CLASSES) \
			   SCALA_FJBG_CLASSES=$(BOOTSTRAP_FJBG_CLASSES) \
			   $(BOOTSTRAP_HOME)/objects/main/bin/scalac

##############################################################################
# Convert tool (ImageMagick)

CONVERT			?= convert
CONVERT_FLAGS		?=

##############################################################################
# XSLT processor

XSLTPROC		?= xsltproc
XSLTPROC_FLAGS		?=

##############################################################################
# Latest files

LATEST_PREFIX		?= .latest

##############################################################################
