############################################################-*-Makefile-*-####
# Project Configuration
##############################################################################
# $Id$

##############################################################################
# Read local configuration

-include $(ROOT)/Makefile.private

##############################################################################
# Project setup

PROJECT_NAME		?= scala
PROJECT_ROOT		?= $(ROOT)
PROJECT_BINARYDIR	?= $(PROJECT_ROOT)/bin
PROJECT_LIBDIR		?= $(PROJECT_LIBRARYDIR)
PROJECT_CONFIGDIR	?= $(PROJECT_ROOT)/config
PROJECT_DOCUMENTDIR	?= $(PROJECT_ROOT)/doc
PROJECT_LIBRARYDIR	?= $(PROJECT_ROOT)/lib
PROJECT_SUPPORTDIR	?= $(PROJECT_ROOT)/support
PROJECT_SOURCEDIR	?= $(PROJECT_ROOT)/sources
PROJECT_OUTPUTDIR	?= $(PROJECT_ROOT)/classes
PROJECT_WEBSITEDIR	?= $(PROJECT_ROOT)/website
PROJECT_HTDOCSDIR	?= $(PROJECT_WEBSITEDIR)/htdocs
PROJECT_DISTRIBDIR	?= $(PROJECT_ROOT)/distribs
PROJECT_ARCHIVEDIR	?= $(PROJECT_DISTRIBDIR)
PROJECT_BOOTSTRAPDIR	?= $(PROJECT_ROOT)/bootstrap
PROJECT_BOOTTESTDIR	?= $(PROJECT_ROOT)/boottest
PROJECT_CLASSPATH	?= $(PROJECT_OUTPUTDIR)
PROJECT_LISTDIR		?= $(PROJECT_CONFIGDIR)/list
PROJECT_APIDOCDIR	?= $(PROJECT_DOCUMENTDIR)/api

##############################################################################
# External libraries

# JDK 8
ENV_JAVA_HOME		:= $(JAVA_HOME)
SCALA_JAVA_HOME		?=
SYSTEM_JAVA8_HOME	:= $(shell if [ -x /usr/libexec/java_home ]; then /usr/libexec/java_home -v 1.8 2>/dev/null; fi)
DEFAULT_JAVA_HOME	:= $(if $(SCALA_JAVA_HOME),$(SCALA_JAVA_HOME),$(if $(SYSTEM_JAVA8_HOME),$(SYSTEM_JAVA8_HOME),$(ENV_JAVA_HOME)))
JAVA_HOME		:= $(DEFAULT_JAVA_HOME)

# JRE
JRE_HOME		?= $(if $(JAVA_HOME),$(JAVA_HOME)/jre,$(PROJECT_LIBDIR)/jre)
JRE_JARFILE		?= $(JRE_HOME)/lib/rt.jar

# FJBG
FJBG_HOME		?= $(PROJECT_LIBDIR)/fjbg
FJBG_JARFILE            ?= $(FJBG_HOME)/fjbg.jar

# Ant
ANT_HOME		?= $(PROJECT_LIBDIR)/ant
ANT_JARFILE		?= $(ANT_HOME)/lib/ant.jar

##############################################################################
# Standard tools

BASENAME		?= basename
BZIP2			?= bzip2
CAT			?= cat
CHMOD			?= chmod
COMM			?= comm
CP			?= cp
CVS			?= cvs
DATE			?= date
DIRNAME			?= dirname
ECHO			?= echo
EXPR			?= expr
FIND			?= find
GREP			?= grep
GZIP			?= gzip
HEAD			?= head
IA			?= build
INSTALL			?= $(PROJECT_SUPPORTDIR)/scripts/install
JAR			= $(if $(JAVA_HOME),$(JAVA_HOME)/bin/jar,jar)
JAVA			= $(if $(JAVA_HOME),$(JAVA_HOME)/bin/java,java)
JAVAC			= $(if $(JAVA_HOME),$(JAVA_HOME)/bin/javac,javac)
LN			?= ln
M4			?= m4
MIRROR			?= $(PROJECT_SUPPORTDIR)/scripts/mirror
MKDIR			?= mkdir
MV			?= mv
NICE			?= nice
RECODE			?= recode
RM			?= rm -f
SCSH			?= scsh
SED			?= sed
SORT			?= sort
STAT			?= stat
TAIL			?= tail
TAR			?= tar
TOUCH			?= touch
TR			?= tr
UNIX2DOS		?= $(RECODE) ..pc
UNZIP			?= unzip
WC			?= wc
XARGS			?= xargs
ZIP			?= zip

make			?= $(MAKE) MAKELEVEL=$(MAKELEVEL) --no-print-directory

##############################################################################
# Java compiler

JAVAC_FLAGS		?= -source 8 -target 8

##############################################################################
# Bootstrap compiler

BOOTSTRAP_SCALAC	?= scalac

##############################################################################
# XSLT processor

XSLTPROC		?= xsltproc
XSLTPROC_FLAGS		?=

##############################################################################
